"""Add field is_price_from in Service model

Revision ID: c189f78e9da1
Revises: 7323be036464
Create Date: 2024-09-27 00:42:22.378870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c189f78e9da1'
down_revision: Union[str, None] = '7323be036464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_price_from', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_price_from')
    # ### end Alembic commands ###
