"""Add total_price field in appointment model

Revision ID: d606e4995fd9
Revises: ec46a0cc4ff3
Create Date: 2024-11-03 12:29:03.860273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd606e4995fd9'
down_revision: Union[str, None] = 'ec46a0cc4ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('total_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'total_price')
    # ### end Alembic commands ###
