"""Add duration field in service model

Revision ID: e2d4d6501ba5
Revises: d606e4995fd9
Create Date: 2024-11-03 12:58:10.972267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d4d6501ba5'
down_revision: Union[str, None] = 'd606e4995fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'duration')
    # ### end Alembic commands ###
