"""Add field name in appointments

Revision ID: c3bf0626ec92
Revises: eaa812102b24
Create Date: 2024-10-19 17:29:10.351633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3bf0626ec92'
down_revision: Union[str, None] = 'eaa812102b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'name')
    # ### end Alembic commands ###
